### ISSUE TITLE
epic v1 cucumber comedy club

### ISSUE THREAD

**Issue by kfarr** [kfarr/cucumber-comedy-club#1]
why?
- silly demo of hand tracking
- have fun
- spark joy in others

Current glitch project: https://glitch.com/edit/#!/cucumber-carl

Useable with instructions
- [ ] - Carl and Carla both -- one on each hand ([carla can be found on the carl rigging issue](https://github.com/3DStreet/3dstreet-assets-source/issues/74))
- [ ] - Remove the switch to choose wrist vs hand, only place in hand
- [ ] - Test using Diego's "+" menu
- [ ] - Find 3 objects: stage + microphone, tables + chairs, mirror?
- [ ] - Using + menu, can pick one of the 3 models and place persistently;
- [ ] - tables and chairs has 2 versions - hover to start clapping, hover to start laughing (laugh track)
- [ ] - test mirror component?
- [ ] - Create title screen - cucumber comedy club
- [ ] - Larger AR button
